server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # Wichtig für Single Page Applications (React/Vite):
        # Wenn eine Datei nicht existiert, leite auf index.html um.
        try_files $uri $uri/ /index.html;
    }
}
