export const BASE_URL = "http://localhost:3000";
export const BACKEND_URL = `${BASE_URL}/api`;

export const PLANT_TYPES = [
  { id: "monstra", label: "Monstera" },
  { id: "anthurium", label: "Anthurium" },
  { id: "orchid", label: "Orchidee" },
  { id: "philodendronmccolleysfinale", label: "Philodendron" },
  { id: "usambaraveilchen", label: "Usambara-Veilchen" },
  { id: "yucca", label: "Yucca" },
  { id: "kalanchoe", label: "Kalanchoe" },
  { id: "peperomiaobtusifolia", label: "Peperomia Obtusifolia" },
  { id: "peperomiarotundifolia", label: "Peperomia Rotundifolia" },
  { id: "iddleleaffig", label: "Fiddle Leaf Fig" },
  { id: "dieffenbachia", label: "Dieffenbachia" },
  { id: "schlumbergera", label: "Schlumbergera" },
  { id: "aloevera", label: "Aloe Vera" },
  { id: "Chlorophytum", label: "Chlorophytum" },
  { id: "calatheaorbifolia", label: "Calathea Orbifolia" },
  { id: "ficuselastica", label: "Ficus elastica" },
  { id: "epipremnumaureum", label: "Epipremnum Aureum" },
  { id: "zamioculcas", label: "Zamioculcas" },
  { id: "sansevieria", label: "Sansevieria" },
  { id: "echinopsissubdenudata", label: "Echinopsis Subdenudata" },
  { id: "mammillariaelongata", label: "Mammillaria Elongata" },
  { id: "opuntiamicrodasys", label: "Opuntia Microdasys" },
  { id: "rebutiaheliosa", label: "Rebutia Heliosa" },
  { id: "sedummorganianum", label: "Sedum Morganianum" },
  { id: "spathiphyllum", label: "Spathiphyllum / Peace Lily" },
  { id: "hibiscusrosasinensis", label: "Hibiscus Rosa-Sinensis" },
  { id: "bromeliaguzmania", label: "Bromelia Guzmania" },
  { id: "cliviaminiata", label: "Clivia Miniata" },
  { id: "gardeniajasminoides", label: "Gardenia Jasminoides " },
];
